services:
  - type: web
    name: bizchat-app
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
    # Enable database migration if DATABASE_URL is provided
    preDeployCommand: |
      if [ -n "$DATABASE_URL" ]; then
        npx drizzle-kit push --force
      else
        echo "No DATABASE_URL provided, skipping database migration"
      fi