services:
  - type: web
    name: bizchat-app
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      # Email service configuration (choose one method)
      # Method 1: Gmail SMTP (Recommended for small scale)
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      # Method 2: SendGrid (Recommended for production)
      - key: SENDGRID_API_KEY
        sync: false
      # Email sender address
      - key: FROM_EMAIL
        sync: false
      # Admin credentials for admin panel access
      - key: ADMIN_EMAIL
        value: admin@bizchat.com
      - key: ADMIN_PASSWORD
        value: admin123456
      - key: ADMIN_NAME
        value: المدير العام
    # Enable database migration if DATABASE_URL is provided
    preDeployCommand: |
      if [ -n "$DATABASE_URL" ]; then
        npx drizzle-kit push --force
      else
        echo "No DATABASE_URL provided, skipping database migration"
      fi