services:
  - type: web
    name: bizchat-app
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run db:push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000